var data=`http://www.jiajuol.com/workman
http://www.jiajuol.com/workman/100004
http://www.jiajuol.com/workman/100005
http://www.jiajuol.com/workman/100006
http://www.jiajuol.com/workman/100013
http://www.jiajuol.com/workman/100018
http://www.jiajuol.com/workman/100021
http://www.jiajuol.com/workman/100023
http://www.jiajuol.com/workman/100031
http://www.jiajuol.com/workman/100034
http://www.jiajuol.com/pic/s1
http://www.jiajuol.com/pic/s16
http://www.jiajuol.com/pic/s19
http://www.jiajuol.com/pic/s19/p2
http://www.jiajuol.com/pic/s1/p10
http://www.jiajuol.com/pic/s1/p11
http://www.jiajuol.com/pic/s1/p12
http://www.jiajuol.com/pic/s1/p13
http://www.jiajuol.com/pic/s1/p14
http://www.jiajuol.com/pic/s1/p15
http://www.jiajuol.com/pic/s1
http://www.jiajuol.com/pic/s16
http://www.jiajuol.com/pic/s19
http://www.jiajuol.com/pic/s19/p2
http://www.jiajuol.com/pic/s1/p10
http://www.jiajuol.com/pic/s1/p11
http://www.jiajuol.com/pic/s1/p12
http://www.jiajuol.com/pic/s1/p13
http://www.jiajuol.com/pic/s1/p14
http://www.jiajuol.com/pic/s1/p15
http://www.jiajuol.com/pic/c17
http://www.jiajuol.com/pic/c18
http://www.jiajuol.com/pic/c20
http://www.jiajuol.com/pic/c21
http://www.jiajuol.com/pic/c22
http://www.jiajuol.com/pic/c22/p10
http://www.jiajuol.com/pic/c22/p2
http://www.jiajuol.com/pic/c22/p3
http://www.jiajuol.com/pic/c22/p4
http://www.jiajuol.com/pic/c22/p5
http://www.jiajuol.com/pic/s1
http://www.jiajuol.com/pic/s16
http://www.jiajuol.com/pic/s19
http://www.jiajuol.com/pic/s19/p2
http://www.jiajuol.com/pic/s1/p10
http://www.jiajuol.com/pic/s1/p11
http://www.jiajuol.com/pic/s1/p12
http://www.jiajuol.com/pic/s1/p13
http://www.jiajuol.com/pic/s1/p14
http://www.jiajuol.com/pic/s1/p15
http://www.jiajuol.com/pic/c17
http://www.jiajuol.com/pic/c18
http://www.jiajuol.com/pic/c20
http://www.jiajuol.com/pic/c21
http://www.jiajuol.com/pic/c22
http://www.jiajuol.com/pic/c22/p10
http://www.jiajuol.com/pic/c22/p2
http://www.jiajuol.com/pic/c22/p3
http://www.jiajuol.com/pic/c22/p4
http://www.jiajuol.com/pic/c22/p5
http://www.jiajuol.com/pic
http://www.jiajuol.com/pic/c17
http://www.jiajuol.com/pic/c18
http://www.jiajuol.com/pic/c20
http://www.jiajuol.com/pic/c21
http://www.jiajuol.com/pic/c22
http://www.jiajuol.com/pic/c22/p10
http://www.jiajuol.com/pic/c22/p2
http://www.jiajuol.com/pic/c22/p3
http://www.jiajuol.com/pic/c22/p4
http://www.jiajuol.com/baike/c1
http://www.jiajuol.com/baike/c2
http://www.jiajuol.com/baike/c29
http://www.jiajuol.com/baike/c2/p3
http://www.jiajuol.com/baike/c3
http://www.jiajuol.com/baike/cs21
http://www.jiajuol.com/baike/cs23
http://www.jiajuol.com/baike/cs30
http://www.jiajuol.com/baike/cs31
http://www.jiajuol.com/baike/cs32
http://www.jiajuol.com/baike
http://www.jiajuol.com/baike/1058
http://www.jiajuol.com/baike/1323
http://www.jiajuol.com/baike/1415
http://www.jiajuol.com/baike/1912
http://www.jiajuol.com/baike/2059
http://www.jiajuol.com/baike/2060
http://www.jiajuol.com/baike/2066
http://www.jiajuol.com/baike/2616
http://www.jiajuol.com/baike/2688
http://news.jiajuol.com/strategy
http://news.jiajuol.com/strategy/col75
http://news.jiajuol.com/strategy/p100
http://news.jiajuol.com/strategy/p101
http://news.jiajuol.com/strategy/p102
http://news.jiajuol.com/strategy/p103
http://news.jiajuol.com/strategy/p104
http://news.jiajuol.com/strategy/p105
http://news.jiajuol.com/strategy/p106
http://news.jiajuol.com/strategy/p107
http://news.jiajuol.com/strategy/col75
http://news.jiajuol.com/strategy/col75
http://news.jiajuol.com/
http://news.jiajuol.com/201003/23291_2.shtml
http://news.jiajuol.com/201003/23291_3.shtml
http://news.jiajuol.com/201003/23291_4.shtml
http://news.jiajuol.com/201003/23291_5.shtml
http://news.jiajuol.com/201003/23291_6.shtml
http://news.jiajuol.com/201003/23291.shtml
http://news.jiajuol.com/201003/23399_10.shtml
http://news.jiajuol.com/201003/23399_2.shtml
http://news.jiajuol.com/201003/23399_3.shtml
http://news.jiajuol.com/column_10.html
http://news.jiajuol.com/column_13.html
http://news.jiajuol.com/column_17.html
http://news.jiajuol.com/column_18.html
http://news.jiajuol.com/column_19.html
http://news.jiajuol.com/column_20.html
http://news.jiajuol.com/column_25.html
http://news.jiajuol.com/column_26.html
http://news.jiajuol.com/column_2.html
http://news.jiajuol.com/column_31.html
http://seller.jiajuol.com/seller
http://seller.jiajuol.com/seller/100000
http://seller.jiajuol.com/seller/100001
http://seller.jiajuol.com/seller/100002
http://seller.jiajuol.com/seller/100003
http://seller.jiajuol.com/seller/100004
http://seller.jiajuol.com/seller/100005
http://seller.jiajuol.com/seller/100006
http://seller.jiajuol.com/seller/100007
http://seller.jiajuol.com/seller/100008
http://seller.jiajuol.com/activity
http://seller.jiajuol.com/activity/100002
http://seller.jiajuol.com/activity/100006
http://seller.jiajuol.com/activity/100009
http://seller.jiajuol.com/activity/100011
http://seller.jiajuol.com/comment
http://seller.jiajuol.com/comment/113
http://seller.jiajuol.com/comment/115
http://seller.jiajuol.com/comment/117
http://seller.jiajuol.com/comment/118
http://seller.jiajuol.com/comment/44
http://seller.jiajuol.com/comment/46
http://seller.jiajuol.com/comment/57
http://seller.jiajuol.com/comment/58
http://seller.jiajuol.com/comment/63
http://seller.jiajuol.com/goods
http://seller.jiajuol.com/goods/100002
http://seller.jiajuol.com/goods/100019
http://seller.jiajuol.com/goods/100025
http://seller.jiajuol.com/goods/100026
http://seller.jiajuol.com/goods/100027
http://seller.jiajuol.com/goods/100028
http://seller.jiajuol.com/goods/100034
http://seller.jiajuol.com/goods/100035
http://seller.jiajuol.com/goods/100036
http://www.jiajuol.com/
http://www.jiajuol.com/workman
http://seller.jiajuol.com/
http://seller.jiajuol.com/seller
http://seller.jiajuol.com/activity
http://seller.jiajuol.com/comment
http://seller.jiajuol.com/goods
http://www.jiajuol.com/package
http://www.jiajuol.com/package/hui/product	
http://news.jiajuol.com`;
module.exports = data;